version: "3.8"

services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      PORT: 8000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
